### ISSUE TITLE
nestjsでreactを使いたい。

### ISSUE THREAD

**Issue by ralian8125** [ralian8125/nestjs_tutorial#2]
これの前はテンプレートエンジン（hbs）を用いて表示していましたが、reactを使いたいです。
自分の認識では以下URLのパッケージをダウンロードすればviewディレクトリのtsxファイルが読み込まれると思っていました。

参考にしたURL  
https://www.npmjs.com/package/nestjs-tsx-views

**Comment by Amka78** [comment]
Reactは、それ自体がnode上で動くアプリケーションです。
Reactを使いたい場合は
1.Reactが動くnodeプロジェクトを作成する。
2.NestJSにRestAPIかGraphQLのエンドポイントを作成し、1のReactアプリと通信する。
上記の構成が必要になります。

個人開発で何かを作られる予定だと思いますが一度何を作りたいかを共有した方がよいかもしれません。
場合によってはReact+NestJSよりも適した構成がある可能性もあります。

**Comment by ralian8125** [comment]
最初に作りたいものはカードゲームの攻略サイトです。
おおまかな要素としては以下です。
1.デッキレシピを投稿出来る。
2.投稿されたレシピに対してのコメントや評価機能。
3.カードや属性等によるデッキ検索

**Comment by Amka78** [comment]
その構成ですとサーバーレスも検討してもよいかもしれません。
https://aws.amazon.com/jp/amplify/
https://firebase.google.com/

React+NestJS+各種DBの構成の場合、必要となる知識としてフロントエンド、バックエンド、インフラ、DBの知識が必要となります。
React+サーバーレスの構成なら基本フロントエンド+サーバーレスAPIの知識だけで実装が可能です。
React+サーバーレスで手早く組んだあとに必要に応じてバックエンドをNestJS等に置換するというのもありでしょう。

もちろん学習を兼ねての個人開発だと思うのでralian8125の考えや方針を基本的に尊重します。

**Comment by ralian8125** [comment]
ありがとうございます。
amplifyの説明を見たところ、これが自分の望んでいた形に近いようです。
（勉強も兼ねてますが、アイデアをどんどん形にしたいため）
とりあえずチュートリアル等しようと思います。

**Comment by ralian8125** [comment]
Amplifyの情報をいくつか見ましたが、自分の作りたいものの構成にしてはオーバースペックな印象がありました。
仮にfirebase(cloudfunctionやgcpのgae)を採用する場合、reactサーバー用とサーバーレスAPI用と2つ用意する感じですか？(フロントサーバーとサーバーサイドを分ける)
個人的なイメージとしては以下です。
クライアント→フロントエンドサーバー(react、next等)→サーバーサイドサーバー(express、nest等)→DB
モノリシックなrailsの構成しか経験が無いため、クラウドを用いた構成や、フロントとサーバーサイドでサーバーを分けるといった構成あたりがよく分からずです。

加えてnextjsを勉強していてapi routesでもAPIは建てれるので、nextjsで完結出来るのではと思いました。
ただ調べてみるとそのような構成が少なく(ブログ系くらい)、よろしくないといった記事がありました。
このあたりについてもご教授いただきたいです。

**Comment by Amka78** [comment]
AmplifyやFirebaseはサーバーレスと呼ばれていますが、これは要は
(バックエンドサーバー+インフラ →DB+インフラ)の部分をAmplifyやFirebaseのAPIという形で隠蔽してくれるものです。
APIの形になるので細かい設定やトラブった際の調査がやっかいという部分がありますがバックエンド、DB、インフラの知識が
なくてもアプリケーションを構築できるメリットがあります。
ですのでNextJS+Amplify、NextJS+Firebaseは実質的にはralian8125さんの言う。
クライアント→フロントエンドサーバー→バックエンドサーバー→DBの構成と同一になります。
バックエンドから後の部分が開発者からみて隠蔽されているか否かしか違いがありません。
AmplifyもFirebaseも多機能なので全部勉強しようとせず、必要なところから学習するというのが良いでしょう。

NextJSは確かにAPIも作れます。
NextJS+DBの構成でアプリの構築が可能です。ただおっしゃるとおり、あまり、この構成でアプリ開発をする人はいないようです。
(おそらく開発現場の多くはフロントエンドとバックエンドで違うチームが開発することが多いため、フロントエンド単体で完結するNextJSのメリットがあまりない)
ただReact自体がWebコンポーネントという形でAPIの実装が可能となる機能を追加する予定があるので今後はNextJS(React)+DBのような構成も増えていくでしょう。

早くアプリを開発したいという気持ちがあると思いますので、とにかくシンプルな構成(NextJS+DB)もしくはWeb上に豊富なドキュメントや知見のある構成(NextJS+サーバーレス)どちらも正解だと思います。

どの構成でも私自身は経験があるので、フィーリングで決めて、ある程度理解が深まったところで妥当な構成に変えていくでも良いと思います。適切なプロダクト選定を行うというのは非常に難しい部分ではありますので、考え始めたらキリがありません。ある程度で見切りをつけて走り始めることも大切です。どの構成でもralian8125さんが作りたいアプリは構築可能ではあると言っておきます。

**Comment by ralian8125** [comment]
説明ありがとうございます。
確かに自分の中で考えすぎていたので、作り上げることを優先し必要なものを学び、継ぎ足ししていこうと思います。
